### PR TITLE
test

### PR DESCRIPTION
**Pull request by ankushbhardwxj**

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@ben-albrecht The script still failed. 
Correct me if I am wrong. 

Step - 1 ` git clone <chapel-repo>`
Directory structure : 
```
Bricks/
utils/
README.rst
checkTomls.bash
chapel/
```

Step 2 : `cd chapel` && `buildChapel` && `make check` && `make mason`

Step 3: cd .. && `git log -m -1 --name-only --pretty="format:"` 
which should give `Bricks/tests/0.0.1.toml`, but in failed build gives `./util/travisScript.bash`
Otherwise, `cd Bricks/tests` and parse source. 
Clone the repo as `newPackage`, `cd newPackage` && `mason publish --ci-check`

**Comment by ankushbhardwxj** [comment]
Also tagging @ronawho here, for more inputs.

**Comment by ben-albrecht** [comment]
@ankingcodes So it seems there is an issue with the return of `git log -m -1 --name-only --pretty="format:"`. Have you been able to test this locally?

Unrelated to the current error: it might be nice to remove the "state" of `PWD` by never changing directories:

```
git clone <chapel>
(cd chapel && buildChapel && make check && make mason)
(cd newPackage && mason publish --ci-check)
```

**Comment by ankushbhardwxj** [comment]
> git log -m -1 --name-only --pretty="format:"

This worked fine for me locally

**Comment by ben-albrecht** [comment]
The issue isn't immediately obvious to me. I would suggest adding some debug prints (that would be useful to leave in long-term anyways), such as:

- the list of files changed (`$package`)
- the source parsed from the TOML files (`$fixed`)

Also, I think we should expect multiple files in `package` string and parse the `.toml` files out of that, then loop over those TOML files and apply `mason publish --ci-check`. I think this will require some bigger changes... That said, let's continue trying to get the minimal example working before expanding to this.

**Comment by ben-albrecht** [comment]
I also wonder if there is any advantage to using `$TRAVIS_BRANCH` (source: https://stackoverflow.com/questions/41145041/list-files-modified-in-a-pull-request-within-travis) -- though that makes local testing more difficult to set up.

**Pull request closed without merging**
