### PR TITLE
Putting in the old working script and leaving new script in for later

### PR DESCRIPTION
**Pull request by oplambeck**
Leaving travisScript in for when 1.20 is ready, reverting back to previous.

### CODE REVIEW

**Review by ben-albrecht — APPROVED** [review]

**Comment by ben-albrecht** [comment]
For anyone picking this up (such as @oplambeck himself), here's the log of the test with the new script: https://travis-ci.com/chapel-lang/mason-registry/builds/125296506

I suspect the cause of failure is due to ` package=$(git log -m -1 --name-only --pretty="format:")` returning something with spaces in it, which causes `cd $(dirname $path)` (line 30) to fail with the error below:

```bash
cd /home/travis/build/chapel-lang/mason-registry/chapel/bin/linux64-x86_64 && ln -s ../../tools/mason/mason mason

./util/travisScript.bash: line 30: /usr/bin/dirname: Argument list too long

./util/travisScript.bash: line 34: /usr/bin/basename: Argument list too long

./util/travisScript.bash: line 35: /usr/bin/basename: Argument list too long

grep: : No such file or directory
```

**Comment by ankushbhardwxj** [comment]
@ben-albrecht I have been debugging this issue, spaces dont affect the dirname command. for example, 
```
$> dirname .chapel/mason-registry/Bricks/0.1.4.toml.end .chapel/mason-registry
.chapel/mason-registry/Bricks
.chapel
```

**Comment by ankushbhardwxj** [comment]
Also, looking at the build, we find that `cd chapel` failed at line 201 too. Maybe that's because, `cd chapel` was done twice ?

**Comment by ankushbhardwxj** [comment]
I think the error is because Travis ran `checkPackage()` inside chapel directory. We need to `cd ..` and then run the function.

**Pull request merged**
