### PR TITLE
Add hello world brick

### PR DESCRIPTION
**Pull request by bmcdonald3**

### CODE REVIEW

**Review by arezaii — DISMISSED** [review]
Looks good, I would sort these keys as that's how they would be printed if you used a `mason` command to rewrite this file. Feel free to add your name to the `author` key

**Comment by bmcdonald3** [comment]
When you say "sort these keys", do you just mean organize them in a way that I think looks nice or is there an actual sort that is done?

**Comment by arezaii** [comment]
> When you say "sort these keys", do you just mean organize them in a way that I think looks nice or is there an actual sort that is done?

Sort them in alphabetical order, basically just swap the last two keys, `source` and `version`.

**Review by arezaii — DISMISSED** [review]

**Comment by bmcdonald3** [comment]
OK, and is that a style thing or does it need to be in that order?

**Comment by arezaii** [comment]
> OK, and is that a style thing or does it need to be in that order?

There isn't any "need", it'll just be re-ordered if you use `mason add` to add a dependency and `mason` rewrites this file is all. Because `mason` uses the `TOML` package to write out `.toml` files, and the `TOML` package sorts the keys before printing to keep the output deterministic.

**Review by arezaii — DISMISSED** [review]

**Review by arezaii — APPROVED** [review]
sorry for misleading you on 'author' vs. 'authors' 🙁

**Pull request merged**
