### PR TITLE
new test

### PR DESCRIPTION
**Pull request by ankushbhardwxj**

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@ben-albrecht The script worked perfectly but it still failed. Maybe something wrong with the project itself. ( I copied Oplambeck's Gnuplot package )

**Comment by ben-albrecht** [comment]
The project does have 2 top-level modules so that explains 1 failure: https://github.com/oplambeck/chapel-gnuplot/tree/master/src

I am not sure why the fork check is failing. That one may be a bug, unless I misunderstand it.

**Comment by ankushbhardwxj** [comment]
Oh ! We didn't clone `mason-registry` inside `$MASON_HOME`. Maybe that explains the error. 
We can either manually clone to `$MASON_HOME` or use a mason command to do that before `mason publish --ci-check`

**Comment by ben-albrecht** [comment]
@ankingcodes - Closing this until we get the this figured out on our developmental repo

**Pull request closed without merging**
