### PR TITLE
Fix yaml file

### PR DESCRIPTION
**Pull request by ankushbhardwxj**
refactored the YAML file to use only matrix

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@ben-albrecht made the changes 👍

**Comment by ankushbhardwxj** [comment]
`travisScript.bash` seems to be running here though

**Comment by ben-albrecht** [comment]
> travisScript.bash seems to be running here though

I think it's running now that this PR contains the correct yaml changes. I see it is failing though.

**Comment by ankushbhardwxj** [comment]
It failed the `travisScript.bash` because the script parses the dirname from the file changed( here `.travis.yml` ). I think we can merge this and I can make another test PR

**Comment by ben-albrecht** [comment]
Any idea how it's getting `newPackage` here? 

https://travis-ci.com/github/chapel-lang/mason-registry/jobs/346813341#L792

**Comment by ankushbhardwxj** [comment]
Okay, consider a PR `$mason_reg_home/Bricks/test/0.0.1.toml`. The script parses the source field from the toml file and clones that repository as `newPackage` inside `$mason_reg_home/Bricks/test`.

**Comment by ankushbhardwxj** [comment]
The script gets the path and Toml file  using the `git` command in the script.

**Review by ben-albrecht — APPROVED** [review]
Looks good.

I wonder if the `travisScript.bash` should include a check to see whether the user is even attempting to add a package to avoid false negatives when making non-package contributions like this one. Something we can think about later.

**Comment by ankushbhardwxj** [comment]
When we parse the dirname using the git command, we get something like `Bricks/test/0.0.1.toml`. 
We could check if the dirname contains keyword "Bricks" and then proceed with `checkPackage`  & `mason publish --ci-check` , else we exit

**Comment by ben-albrecht** [comment]
That sounds good.  One other sanity check would be to make sure no `.toml` files were being added/modified to ensure someone isn't trying to add a package to somewhere outside of Bricks.

I'm going to merge this now and we can tackle that post-merge.

**Pull request merged**
