### PR TITLE
Add ct-clmsn's LinearAlgebraJama package

### PR DESCRIPTION
**Pull request by benharsh**

### CODE REVIEW

**Comment by benharsh** [comment]
@ct-clmsn : still interested in listing these packages?

**Comment by benharsh** [comment]
@ct-clmsn: I'm going to leave MatrixMarket out until it's git-tagged. Thanks for LinearAlgebraJama!

**Comment by ct-clmsn** [comment]
@benharsh I've tagged the MatrixMarket project. Apologies for not making that happen earlier. Also added a license file and contributors file.

**Comment by ct-clmsn** [comment]
@benharsh I was able to get the MatrixMarket repository properly tagged. Apologies for the delay.

**Comment by benharsh** [comment]
No problem, thanks for jumping on it! I'll open another registry PR shortly.

**Pull request merged**
